### ISSUE TITLE
Getting Foreign Key Constraint Failure in Delete by ID method  In Playlist implementation 

### ISSUE THREAD

**Issue by Aloy-Lockness11** [DraganD-Ukr/Web-Patterns-CA1#12]
Hello, I have come across a foreign key constraint issue. The probable cause is the reference is not deleted from the playlistsong connection table 
```java
public boolean deletePlaylistByID(int playlistId){}
```

**Comment by Aloy-Lockness11** [comment]
Can I make changes and to cascade delete all the references to that playlist if need be

**Comment by DraganD-Ukr** [comment]
Fixed: added cascades to sql scripts
