### ISSUE TITLE
Default Parameter and Constraint of Song table Causing Issues with addSong method Implementation

### ISSUE THREAD

**Issue by Aloy-Lockness11** [DraganD-Ukr/Web-Patterns-CA1#7]
Hey @DraganD-Ukr  I just found an issue where my add song where i cannot add a song to the table cause of this error

`Check constraint 'songs_chk_1' is violated.`

After investigation, I found out that it is the average ratting that is causing the issue, i cannot leave the parameter empty (not include average rating setter), I cannot keep it null cause i get a `type double` error, I have to keep it at 1 and only then it works. This cannot be
because there is no ratings to begin with, I would  suggest a correction be made to reduce the ratting limit to 0 and make the default 0 instead  of null.

![image](https://github.com/user-attachments/assets/65d1d1f4-8920-4f38-a773-13aaa15e11e7)

![image](https://github.com/user-attachments/assets/2ac3fdcd-2055-4bef-aa33-6814a7305630)

**Comment by DraganD-Ukr** [comment]
@Aloy-Lockness11 i totally agree with your suggestion. To be honest, i don't know why it's set to default null, instead of 0.
Let me know if it works for you

**Comment by Aloy-Lockness11** [comment]
I have currently tried it out with default 0 and it works as intended

**Comment by DraganD-Ukr** [comment]
Great, nice to hear that. Thanks for fixing it though! Closing the issue
